applications/autor/urls.py
from django.contrib import admin
from django.urls import path

from .import views

urlpatterns = [
    path('genero_libros/', views.Libros_genero.as_view(), name="genero"),
    path('autor_pais/', views.Autores_pais.as_view(), name="autor"),
    
]

applications/libro/urls.py
from django.contrib import admin
from django.urls import path

from .import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('libros/', views.ListLibros.as_view(), name="listar_libros"),
    path('libro_filtrar/', views.Genero_libro.as_view(), name="genero"),
]

applications/resenia/urls.py
from django.urls import path

from .import views

urlpatterns = [
    path('reseña/<int:pk>/', views.Promedio_resenia.as_view(), name="detalle_libro"),
    
]

libreria/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('applications.libro.urls')),
    re_path('',include('applications.autor.urls')),
    re_path('',include('applications.resenia.urls')),

]

applications/autor/models.py
from django.db import models
from .managers import LibroManager
# Create your models here.

class Autor(models.Model):
    first_name = models.CharField( max_length=30)
    last_name = models.CharField(max_length=30)
    birth_date = models.DateField( blank=True, null=True)
    country = models.CharField( max_length=50)
    
    objects = LibroManager()
    def __str__(self):
        return self.first_name +'-'+ self.last_name
    
class Genero(models.Model):
    name = models.CharField( max_length=20)

    objects = LibroManager()
    def __str__(self):
        return self.name 
    

applications/libro/models.py
from django.db import models
from applications.autor.models import Autor, Genero
from .managers import *
# Create your models here.

class Libro(models.Model):
    title = models.CharField( max_length=50)
    publication = models.DateField(blank=False)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genero, on_delete=models.CASCADE, related_name='libro_genero')
    synopsis = models.CharField(max_length=100)

    objects = LibroManager() 
    
    def __str__(self):
        return self.title 
    

applications/resenia/models.py
from django.db import models
from .managers import ReseniaManager
from applications.libro.models import Libro
from django.core.exceptions import ValidationError
# Create your models here.

class Resenia(models.Model):
    book = models.ForeignKey(Libro, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=3, decimal_places=1)
    review_text = models.CharField(max_length=50)
    created_at = models.DateField( auto_now=False, auto_now_add=False)

    def clean(self):
        # Validación para asegurar que la calificación esté entre 1.0 y 5.0
        if self.rating < 1.0 or self.rating > 5.0:
            raise ValidationError('La calificación debe estar entre 1.0 y 5.0.')
        super().clean()  # Llamar a la validación de Django

    objects = ReseniaManager()

    def __str__(self):
        return self.book.title + ' - '+ str(self.rating)

applications/autor/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView
from .models import Genero, Autor

# Create your views here.

class Libros_genero(ListView):
    context_object_name = 'generos'
    template_name = 'genero/listar.html'

    def get_queryset(self):

         
        return Genero.objects.listar_genero_libros()
    
class Autores_pais(ListView):
    context_object_name = 'autores'
    template_name = 'autor/listar.html'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword','')

        return Autor.objects.autores_pais(palabra_clave)

applications/libro/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView,TemplateView

from .models import Libro
from .models import Genero
from applications.autor.models import Autor
# Create your views here.

class Home(TemplateView):
    template_name = 'base.html'

class ListLibros(ListView):

    context_object_name = 'listar_libros'
    template_name = 'libro/listar.html'

    def get_queryset(self):

        palabra_clave = self.request.GET.get('kword','') 
        return Libro.objects.filter(title__icontains=palabra_clave)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kword'] = self.request.GET.get('kword', '')  # Para mostrar el término de búsqueda actual
        return context
    

class Genero_libro(ListView):
    context_object_name = 'lista_libros'
    template_name = 'libro/listar.html'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword','')

        return Libro.objects.listar_libros_genero(palabra_clave)

    
        

applications/resenia/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Resenia
from .models import Libro
# Create your views here.

class Promedio_resenia(DetailView):
    model = Libro
    context_object_name = 'libro'
    template_name = 'resenia/listar.html'

    def get_context_data(self,**kwargs):

        context =super().get_context_data(**kwargs)
        book_id = self.object.id
        promedio =  Resenia.objects.promedio_resenia(book_id)
        context['promedio_calificacion'] = promedio.get('promedio_calificacion', 0)
        return context

templates/autor/listar.html
{% extends 'base.html'%}
{% load static %}
<h1>Listar libros</h1>

<form method="GET">{% csrf_token %}

    <input type="text" id="kword" name="kword" placeholder="Buscar">
    <button type="submit">Buscar</button>

</form>


<ul>
    {% for autor in autores %}
        <li> {{ autor.first_name}} {{ autor.last_name}}</li>
        
        <ul>
            {% for libro in autor.libro_set.all %}
                
                
                <li> {{ libro.title}}</li>
                
            {% endfor %}
        </ul>
        
        
    {% endfor %}
</ul>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Libreria</title>
</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#!">Studio</a>
            <!-- Search widget-->
            <div class="card-body">
                <form method="GET" action="{% url 'listar_libros' %}">
                    <div class="input-group">
                        <!-- Input para el término de búsqueda -->
                        <input class="form-control" type="text" name="kword"
                            placeholder="Libro,Autor...." aria-label="Enter search term..."
                            aria-describedby="button-search" required />

                        <!-- Botón para enviar el formulario -->
                        <button class="btn bg-secondary" id="button-search" type="submit">
                            Go!
                        </button>
                    </div>
                </form>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home'%}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock nav %}

    {% block content %}
    <!-- Page content-->
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <!-- Post content-->
                <article>
                    <!-- Post header-->
                    <header class="mb-4">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">Bienvenido a libreria studio</h1>

                    </header>
                    <!-- Preview image figure-->
                    <figure class="mb-4"><img class="img-fluid rounded"
                            src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                    <!-- Post content-->
                    <section class="mb-5">
                        <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the
                            free human mind. Because it transforms who we are, how we live, and it gives us an
                            understanding of our place in the universe.</p>
                        <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it
                            are everywhere, so there's no reason to think that Earth would be unique in that regard.
                            Whether of not the life became intelligent is a different question, and we'll see if we find
                            that.</p>
                        <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and
                            carry enough energy into our system to disrupt transportation, communication, the food
                            chains, and that can be a really bad day on Earth.</p>
                        <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                        <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic
                            thoughts every day and I realized I could hold them to myself or share them with people who
                            might be interested.</p>
                        <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened
                            there because we're twirling knobs here on Earth without knowing the consequences of it.
                            Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                    </section>
                </article>
                <!-- Comments section-->
                <section class="mb-5">
                    <div class="card bg-light">
                        <div class="card-body">
                            <!-- Comment form-->
                            <form class="mb-4"><textarea class="form-control" rows="3"
                                    placeholder="Join the discussion and leave a comment!"></textarea></form>
                            <!-- Comment with nested comments-->
                            <div class="d-flex mb-4">
                                <!-- Parent comment-->
                                <div class="flex-shrink-0"><img class="rounded-circle"
                                        src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    If you're going to lead a space frontier, it has to be government; it'll never be
                                    private enterprise. Because the space frontier is dangerous, and it's expensive, and
                                    it has unquantified risks.
                                    <!-- Child comment 1-->
                                    <div class="d-flex mt-4">
                                        <div class="flex-shrink-0"><img class="rounded-circle"
                                                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">Commenter Name</div>
                                            And under those conditions, you cannot establish a capital-market evaluation
                                            of that enterprise. You can't get investors.
                                        </div>
                                    </div>
                                    <!-- Child comment 2-->
                                    <div class="d-flex mt-4">
                                        <div class="flex-shrink-0"><img class="rounded-circle"
                                                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">Commenter Name</div>
                                            When you put money directly to a problem, it makes a good headline.
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Single comment-->
                            <div class="d-flex">
                                <div class="flex-shrink-0"><img class="rounded-circle"
                                        src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    When I look at the universe and all the ways the universe wants to kill us, I find
                                    it hard to reconcile that with statements of beneficence.
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <!-- Side widgets-->
            <div class="col-lg-4">

                <!-- Categories widget-->
                <div class="card mb-4 ">
                    <div class="card-header">Categories</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">Web Design</a></li>
                                    <li><a href="#!">HTML</a></li>
                                    <li><a href="#!">Freebies</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">JavaScript</a></li>
                                    <li><a href="#!">CSS</a></li>
                                    <li><a href="#!">Tutorials</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    {% endblock content %}
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2024</p>
        </div>
    </footer>


    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/genero/listar.html
{% extends 'base.html' %}
<h1>Listar libros</h1>

<form method="GET">{% csrf_token %}

    <input type="text" id="kword" name="kword" placeholder="Buscar">
    <button type="submit">Buscar</button>

</form>


<ul>
    {% for genero in generos %}
        <li> {{ genero.name }}</li>
        <li> {{ genero.publication}}</li>
        
    {% endfor %}
</ul>

templates/libro/listar.html
 {% extends "base.html" %}


{% block content %}

<p> Buscaste: "{{ kword }}" </p>

<ul>
    {% for  libro in listar_libros %}
    <h2 > Titulo: <span class="badge bg-info"> {{ libro.title }} </span></h2>
    {{ libro.autor.first_name }} 
    {% empty %}
        <p>No se encontraron resultados para tu búsqueda.</p>
    {% endfor %}
</ul>

<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">An item</li>
      <li class="list-group-item">A second item</li>
      <li class="list-group-item">A third item</li>
    </ul>
    <div class="card-body">
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>


{% endblock content %}

templates/resenia/listar.html
{% extends 'base.html' %}
<h1>{{ libro.title }}</h1>
<p>Autor: {{ libro.autor.first_name }} {{ libro.autor.last_name }}</p>
<p>Promedio de calificaciones: {{ promedio_calificacion }}</p>

<strong>Calificación:</strong> {{ resenia.rating }}<br>
<strong>Comentario:</strong> {{ resenia.review_text }}